# SQLite for local development and test
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# PostgreSQL for Cloud Deployment
# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code.
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate